name: "Rails ToDo App CI"
on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, closed]
    branches: [ "main" ]
    
permissions:
  contents: read

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        ruby-version: [3.0.0]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - name: Install Dependencies
      run: |
        gem install bundler
        bundle install

    - name: Run RSpec Tests
      run: bundle exec rspec --format documentation

    - name: Run Minitests
      run: bin/rails test:all --verbose

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0
      - run: gem install rubocop rubocop-rails
      - name: Run Rubocop Lint
        run: rubocop --require rubocop-rails
